### ISSUE TITLE
Deleted accounts appear in cohort list if related rule uses logical operator OR

### ISSUE THREAD

**Issue by bmoschr** [catalyst/moodle-tool_dynamic_cohorts#102]
How can I exclude deleted users from my rules?

**Comment by dmitriim** [comment]
According to this code https://github.com/catalyst/moodle-tool_dynamic_cohorts/blob/MOODLE_404_STABLE/classes/condition_manager.php#L261 deleted users should be excluded. 

Are you on the latest version of the plugin? If so can you please provide steps to replicate?

**Comment by bmoschr** [comment]
Right now I'm using the version 2024051000 on moodle 4.1.11+ (Build: 20240614). 

My steps:
- I'm using an rule I set up I guess two releases ago
- In the rule I'm using the OR operator on 5 condition based on the user standard profile field title (jobrole)
- the option bulk processing is checked 
- the rule is active 

and I have deactivated the setting 'release members' on the plugin setting page

**Comment by bmoschr** [comment]
Does the latest patch also include old rules?

**Comment by dmitriim** [comment]
Thanks @bmoschr! I was able to replicate this issue for a rule with logical operator OR

**Comment by dmitriim** [comment]
Should be fixed.
