### ISSUE TITLE
Condition: course enrolment

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-tool_dynamic_cohorts#42]
Enrolled in a course X with (optional) enrolment method and (optional) role and (optional) enrolment start date.

**Comment by MURBASLMS** [comment]
in our case thinking along the lines of:

is a Unit coordinator (custom course role based on manager) in any unit (mdl course) 
or in unit A or B, or C
or ideally any unit with course shortname prefix ICT* (eg ICT101s1_24)

the prefix method is our only current way to ID a set of units for a discipline, currently we have no way to identify a unit as say belonging to x school. I imagine that would be done via course custom fields at some point. 

a nice to have.

**Comment by MURBASLMS** [comment]
looking at the mdl user filters, could be possible to infer from:

course role in category
our staff department field populated from HR

to get UC role in courses for school. 

but probably better tied to the course "owner" school.

**Comment by dmitriim** [comment]
A new condition has been added.
