### ISSUE TITLE
Improvement: Menu hiding in global groups

### ISSUE THREAD

**Issue by stdoma** [catalyst/moodle-tool_dynamic_cohorts#62]
Hello!
If a global group is used in the plugin, you get a hint in the overview of the global groups (source).
The edit menu appears regularly at the entry (Gear wheel). The buttons in the menu have no effect on triggering a sub-function.

In this plugin: https://moodle.org/plugins/local_profilecohort
the menu is completely hidden if a global group is controlled via it.

I think that completely hiding it creates less confusion.

**Comment by dmitriim** [comment]
Hi @stdoma 
Can you please supply screenshots to support this issue? It's not very clear what you are talking about here.
Assuming it's about cohorts (not groups) and control for each cohort on the cohort management screen. If it is, then seems like core manages that nicely as long as a cohort gets controlled by the plugin.

See screenshots above. 

![image](https://github.com/catalyst/moodle-tool_dynamic_cohorts/assets/4626431/11dba305-b104-48d5-bffa-18de206729b8)

![image](https://github.com/catalyst/moodle-tool_dynamic_cohorts/assets/4626431/f6972eed-caf9-42bc-879a-4d526a52e5cb)
