### ISSUE TITLE
Release members once a cohort is not managed by the plugin

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-tool_dynamic_cohorts#80]
Should we release users from a cohort once it's not managed by the plugin anymore?

**Comment by MURBASLMS** [comment]
i would think perhaps not, at least for caution. Cohort could be being used for enrolment in something in which case it would suspend users in the course at least. I don't see much harm in leaving as is at the time of releasing management, but i suppose some indication would be useful in the cohort fields. Than again whoever did that would be an admin level so should be able to know and mitigate any risk.

**Comment by dmitriim** [comment]
We may hide this option behind a global setting.

**Comment by dmitriim** [comment]
This has been implemented.
