### ISSUE TITLE
Missing string

### ISSUE THREAD

**Issue by ewallah** [catalyst/moodle-tool_dynamic_cohorts#86]
Debugging: Invalid get_string() identifier: 'privacy:metadata:tool_dynamic_cohorts:ruleid' or component 'tool_dynamic_cohorts'. Perhaps you are missing $string['privacy:metadata:tool_dynamic_cohorts:ruleid'] = ''; in admin/tool/dynamic_cohorts/lang/en/tool_dynamic_cohorts.php

**Comment by dmitriim** [comment]
Should be fixed now
